name: Dev

on:
  push:
    branches: main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
        with:
          path: "dev"

      - name: Install dependencies
        run: cd dev && pnpm install

      - name: Build
        run: cd dev && pnpm run build
